kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cephfs-claim
  namespace: test
spec:
  accessModes:     
    - ReadWriteOnce
  storageClassName: dynamic-cephfs
  resources:
    requests:
      storage: 2Gi
