apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: test
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30004
  selector:
    app: grafana

